"""Initial migration

Revision ID: bc419755b394
Revises: 
Create Date: 2025-07-17 11:51:26.267419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc419755b394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endividamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=255), nullable=False),
    sa.Column('numero_proposta', sa.String(length=255), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento_final', sa.Date(), nullable=False),
    sa.Column('taxa_juros', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tipo_taxa_juros', sa.String(length=10), nullable=False),
    sa.Column('prazo_carencia', sa.Integer(), nullable=True),
    sa.Column('valor_operacao', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fazenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('tamanho_total', sa.Float(), nullable=False),
    sa.Column('area_consolidada', sa.Float(), nullable=False),
    sa.Column('tamanho_disponivel', sa.Float(), nullable=False),
    sa.Column('tipo_posse', sa.Enum('PROPRIA', 'ARRENDADA', 'COMODATO', 'POSSE', name='tipoposse'), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('recibo_car', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fazenda', schema=None) as batch_op:
        batch_op.create_index('idx_fazenda_estado_municipio', ['estado', 'municipio'], unique=False)
        batch_op.create_index('idx_fazenda_tipo_posse', ['tipo_posse'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_fazenda_municipio'), ['municipio'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_tipo_posse'), ['tipo_posse'], unique=False)

    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_index('idx_pessoa_nome_cpf', ['nome', 'cpf_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_cpf_cnpj'), ['cpf_cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoa_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_nome'), ['nome'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=512), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('hectares', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('CERTIDOES', 'CONTRATOS', 'DOCUMENTOS_AREA', 'OUTROS', name='tipodocumento'), nullable=False),
    sa.Column('tipo_personalizado', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('fazenda_id', sa.Integer(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('emails_notificacao', sa.Text(), nullable=True),
    sa.Column('prazos_notificacao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index('idx_documento_tipo_vencimento', ['tipo', 'data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_tipo'), ['tipo'], unique=False)

    op.create_table('endividamento_fazenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=True),
    sa.Column('hectares', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endividamento_pessoa',
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('endividamento_id', 'pessoa_id')
    )
    op.create_table('historico_notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacao', sa.String(length=20), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('emails_enviados', sa.Text(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao_endividamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('emails', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_fazenda',
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pessoa_id', 'fazenda_id')
    )
    with op.batch_alter_table('pessoa_fazenda', schema=None) as batch_op:
        batch_op.create_index('idx_pessoa_fazenda', ['pessoa_id', 'fazenda_id'], unique=False)

    op.create_table('endividamento_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endividamento_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('hectares_utilizados', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['endividamento_id'], ['endividamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endividamento_area')
    with op.batch_alter_table('pessoa_fazenda', schema=None) as batch_op:
        batch_op.drop_index('idx_pessoa_fazenda')

    op.drop_table('pessoa_fazenda')
    op.drop_table('parcela')
    op.drop_table('notificacao_endividamento')
    op.drop_table('historico_notificacao')
    op.drop_table('endividamento_pessoa')
    op.drop_table('endividamento_fazenda')
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_tipo'))
        batch_op.drop_index(batch_op.f('ix_documento_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_documento_nome'))
        batch_op.drop_index(batch_op.f('ix_documento_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_documento_data_vencimento'))
        batch_op.drop_index('idx_documento_tipo_vencimento')

    op.drop_table('documento')
    op.drop_table('auditoria')
    op.drop_table('area')
    op.drop_table('usuario')
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoa_nome'))
        batch_op.drop_index(batch_op.f('ix_pessoa_email'))
        batch_op.drop_index(batch_op.f('ix_pessoa_cpf_cnpj'))
        batch_op.drop_index('idx_pessoa_nome_cpf')

    op.drop_table('pessoa')
    with op.batch_alter_table('fazenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fazenda_tipo_posse'))
        batch_op.drop_index(batch_op.f('ix_fazenda_nome'))
        batch_op.drop_index(batch_op.f('ix_fazenda_municipio'))
        batch_op.drop_index(batch_op.f('ix_fazenda_matricula'))
        batch_op.drop_index(batch_op.f('ix_fazenda_estado'))
        batch_op.drop_index('idx_fazenda_tipo_posse')
        batch_op.drop_index('idx_fazenda_estado_municipio')

    op.drop_table('fazenda')
    op.drop_table('endividamento')
    # ### end Alembic commands ###
