"""Add PessoaFazenda intermediate model and remove tipo_posse from Fazenda

Revision ID: d2617e502515
Revises: bc419755b394
Create Date: 2025-07-17 11:58:40.563588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2617e502515'
down_revision = 'bc419755b394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_documento_data_vencimento'))
        batch_op.drop_index(batch_op.f('idx_documento_tipo'))

    with op.batch_alter_table('endividamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_endividamento_banco'))
        batch_op.drop_index(batch_op.f('idx_endividamento_created_at'))
        batch_op.drop_index(batch_op.f('idx_endividamento_data_vencimento'))

    with op.batch_alter_table('fazenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fazenda_tipo_posse'))
        batch_op.drop_index(batch_op.f('ix_fazenda_tipo_posse'))
        batch_op.drop_column('tipo_posse')

    with op.batch_alter_table('historico_notificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_historico_notificacao_data'))

    with op.batch_alter_table('notificacao_endividamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notificacao_endividamento_ativo'))

    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_parcela_data_vencimento'))
        batch_op.drop_index(batch_op.f('idx_parcela_endividamento_id'))
        batch_op.drop_index(batch_op.f('idx_parcela_pago'))

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pessoa_cpf_cnpj'))
        batch_op.drop_index(batch_op.f('idx_pessoa_nome'))

    with op.batch_alter_table('pessoa_fazenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo_posse', sa.Enum('PROPRIA', 'ARRENDADA', 'COMODATO', 'POSSE', name='tipoposse'), nullable=False))
        batch_op.drop_index(batch_op.f('idx_pessoa_fazenda'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa_fazenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pessoa_fazenda'), ['pessoa_id', 'fazenda_id'], unique=False)
        batch_op.drop_column('tipo_posse')
        batch_op.drop_column('id')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pessoa_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('idx_pessoa_cpf_cnpj'), ['cpf_cnpj'], unique=False)

    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_parcela_pago'), ['pago'], unique=False)
        batch_op.create_index(batch_op.f('idx_parcela_endividamento_id'), ['endividamento_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_parcela_data_vencimento'), ['data_vencimento'], unique=False)

    with op.batch_alter_table('notificacao_endividamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notificacao_endividamento_ativo'), ['ativo'], unique=False)

    with op.batch_alter_table('historico_notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_historico_notificacao_data'), ['data_envio'], unique=False)

    with op.batch_alter_table('fazenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_posse', sa.VARCHAR(length=9), nullable=False))
        batch_op.create_index(batch_op.f('ix_fazenda_tipo_posse'), ['tipo_posse'], unique=False)
        batch_op.create_index(batch_op.f('idx_fazenda_tipo_posse'), ['tipo_posse'], unique=False)

    with op.batch_alter_table('endividamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_endividamento_data_vencimento'), ['data_vencimento_final'], unique=False)
        batch_op.create_index(batch_op.f('idx_endividamento_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_endividamento_banco'), ['banco'], unique=False)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_documento_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_documento_data_vencimento'), ['data_vencimento'], unique=False)

    # ### end Alembic commands ###
