"""Estado inicial completo

Revision ID: e8d2ebcf51cd
Revises: 
Create Date: 2025-07-18 01:14:25.277627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d2ebcf51cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removidas operações problemáticas que causam conflitos com chaves estrangeiras
    # Marcando este como o estado atual do banco de dados
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa_fazenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_posse', mysql.ENUM('PROPRIA', 'ARRENDADA', 'COMODATO', 'POSSE', collation='utf8mb4_unicode_ci'), server_default=sa.text("'PROPRIA'"), nullable=False))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('data_fim', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio', sa.DATE(), nullable=False))
        batch_op.drop_index('idx_pessoa_fazenda')
        batch_op.create_index(batch_op.f('ix_pessoa_fazenda_tipo_posse'), ['tipo_posse'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_fazenda_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_fazenda_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pessoa_fazenda_unico'), ['pessoa_id', 'fazenda_id', 'tipo_posse'], unique=True)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pessoa_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('idx_pessoa_cpf_cnpj'), ['cpf_cnpj'], unique=False)

    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_parcela_pago'), ['pago'], unique=False)
        batch_op.create_index(batch_op.f('idx_parcela_endividamento_id'), ['endividamento_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_parcela_data_vencimento'), ['data_vencimento'], unique=False)

    with op.batch_alter_table('notificacao_endividamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('destinatarios', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('conteudo', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notificacao_endividamento_ibfk_1'), 'endividamento', ['endividamento_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notificacao_endividamento_tipo_notificacao'))
        batch_op.drop_index(batch_op.f('ix_notificacao_endividamento_enviado'))
        batch_op.drop_index(batch_op.f('ix_notificacao_endividamento_endividamento_id'))
        batch_op.drop_index(batch_op.f('ix_notificacao_endividamento_data_envio'))
        batch_op.drop_index(batch_op.f('ix_notificacao_endividamento_ativo'))
        batch_op.drop_index('idx_notif_endiv_tipo')
        batch_op.drop_index('idx_notif_endiv_ativa_pendente')
        batch_op.create_index(batch_op.f('idx_notificacao_pendente'), ['ativo', 'enviado', 'data_envio'], unique=False)
        batch_op.create_index(batch_op.f('idx_notificacao_endividamento_tipo'), ['tipo_notificacao'], unique=False)
        batch_op.create_index(batch_op.f('idx_notificacao_endividamento_enviado'), ['enviado'], unique=False)
        batch_op.create_index(batch_op.f('idx_notificacao_endividamento_data_envio'), ['data_envio'], unique=False)
        batch_op.create_index(batch_op.f('idx_notificacao_endividamento_ativo'), ['ativo'], unique=False)
        batch_op.alter_column('data_envio',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('tipo_notificacao',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.drop_column('erro_mensagem')
        batch_op.drop_column('tentativas')
        batch_op.drop_column('data_envio_realizado')

    with op.batch_alter_table('historico_notificacao_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emails_enviados', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_historico_notificacao_documento_documento_id'))
        batch_op.drop_index('idx_historico_notificacao_documento_tipo')
        batch_op.drop_index('idx_historico_notificacao_documento_data')
        batch_op.create_index(batch_op.f('idx_historico_notificacao_documento'), ['documento_id'], unique=False)
        batch_op.alter_column('tipo_notificacao',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('dias_restantes',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('erro_mensagem')
        batch_op.drop_column('sucesso')
        batch_op.drop_column('destinatarios')

    with op.batch_alter_table('historico_notificacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historico_notificacao_ibfk_1'), 'endividamento', ['endividamento_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_historico_notificacao_endividamento_id'))
        batch_op.drop_index(batch_op.f('ix_historico_notificacao_data_envio'))
        batch_op.drop_index('idx_historico_notif_tipo')
        batch_op.drop_index('idx_historico_notif_sucesso')
        batch_op.drop_index('idx_historico_notif_data')
        batch_op.create_index(batch_op.f('idx_historico_notificacao_endividamento'), ['endividamento_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_historico_notificacao_data'), ['data_envio'], unique=False)
        batch_op.alter_column('data_envio',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('notificacao_id')

    with op.batch_alter_table('fazenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fazenda_tipo_posse'))
        batch_op.drop_index('idx_fazenda_tipo_posse')
        batch_op.drop_column('tipo_posse')

    with op.batch_alter_table('endividamento_area', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('endividamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_endividamento_data_vencimento'), ['data_vencimento_final'], unique=False)
        batch_op.create_index(batch_op.f('idx_endividamento_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_endividamento_banco'), ['banco'], unique=False)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_responsavel_id'))
        batch_op.drop_index('idx_documento_status_processamento')
        batch_op.drop_index('idx_documento_ativo')
        batch_op.create_index(batch_op.f('idx_documento_vencimento_status'), ['data_vencimento', 'ativo'], unique=False)
        batch_op.create_index(batch_op.f('idx_documento_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_documento_processamento'), ['status_processamento'], unique=False)
        batch_op.create_index(batch_op.f('idx_documento_data_vencimento'), ['data_vencimento'], unique=False)

    # ### end Alembic commands ###
